

INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (1, 2);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (4, 8);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (4, 5);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (1, 6);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (2, 9);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (4, 4);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (3, 5);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (2, 8);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (3, 1);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (1, 3);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (2, 10);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (3, 10);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (2, 2);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (5, 8);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (5, 9);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (10, 10);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (10, 2);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (5, 1);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (9, 9);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (9, 6);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (5, 6);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (8, 3);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (8, 4);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (7, 2);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (7, 5);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (5, 7);
INSERT INTO project_worker (PROJECT_ID, WORKER_ID) VALUES (6, 3);




